remote_theme: contributorcoin/contributorcoin-jekyll-theme@v0.1.4

title: Contributorcoin Whitepaper
description: The source of information about the open-source cryptocurrency
show_downloads:
show_gh_edit: true
show_toc: true
google_analytics:
toc_title: 
