remote_theme: contributorcoin/contributorcoin-jekyll-theme@v0.1.5

title: Contributorcoin Whitepaper
description: Official information and philosophies for Contributorcoin
show_downloads:
show_gh_edit: true
show_toc: true
google_analytics:
toc_title: 
